// make it easier to change routes by defining them in one place
export const routes = {
    // 'home': '/',
    'home': '/monkey',
    'monkey': '/monkey',
    'monkeyGettingStarted': '/monkey/getting-started',
    'monkeyManual': '/monkey/manual',
    'monkeyTemplates': '/monkey/templates',
    'monkeyFaq': '/monkey/faq',
    'monkeyChangelog': '/monkey/changelog',
    'monkeyConnect': '/resources/guides/monkey-connect',
    'kd3': '/KD-3',
    'bridge': '/bridge',
    'midiConnect': '/MIDI-connect',
    'blog': '/blog',
    'support': '/support',
    'about': '/about',
    'partners': '/partners',

    'deviceUtility': '/resources/device-utility',
    'deviceUtilityPlayground': '/resources/device-utility#playground',
    'faq': '/resources/faq',
    'downloads': '/resources/downloads',
    'termsAndConditions': '/resources/terms-and-conditions',
    'wavyDiscord': 'https://discord.gg/4HQHERUW5K',
    'midiConnectAppStore': 'https://apps.apple.com/no/app/midi-toolbar/id6476070288?mt=12',
    'midiConnectWindowsInstaller': '/assets/MIDI-Connect/MIDI_Connect_Setup_0.1.0.exe',
    'wavyIndstagram': 'https://www.instagram.com/wavyindustries_/',
}
